### ISSUE TITLE
Use the libzim.a generated by kiwix-build

### ISSUE THREAD

**Issue by mossroy** [openzim/javascript-libzim#12]
The Makefile could be modified to take a provided libzim.a (from the CI), instead of recompiling it from scratch

Beware of the potential issues that could happen if different versions of emscripten are used to compile libzim.a and this Makefile

**Comment by Jaifroid** [comment]
Some useful information for testing the build failures when building with `libzim.a` and dependencies from kiwix-buils:

* https://github.com/openzim/javascript-libzim/issues/9#issuecomment-1323414741
* https://github.com/kiwix/kiwix-build/issues/552#issuecomment-1334691832

In short, they appear to build correctly, but we are getting index and memory out of bounds errors in the console.log when using the WASM.

**Comment by Jaifroid** [comment]
@kelson42 If we have stable nightly and release builds of the libzim WASM binaries, as it seems we will from https://github.com/openzim/libzim/issues/751, I'll be happy to work on this issue. But to do so, I need to merge #14, so that I'm not mixing up the issues in one enormous PR, and to keep the commit history logical. Could you kindly approve #14 so that I can continue (I could do some work on this on Thursday)?

**Comment by kelson42** [comment]
@mgautierfr Please make a new build of libzim so @Jaifroid can benefit of a stable version and not rely anymore on any nightly here.

**Comment by kelson42** [comment]
@Jaifroid Release has been done again. https://download.openzim.org/release/libzim/libzim_wasm-emscripten-8.1.0-1.tar.gz

Should be good now.

**Comment by Jaifroid** [comment]
> @Jaifroid Release has been done again. https://download.openzim.org/release/libzim/libzim_wasm-emscripten-8.1.0-1.tar.gz
> 
> Should be good now.

Excellent, I'll get to it.

**Comment by Jaifroid** [comment]
@mgautierfr You'll be pleased to know that this Repo is now building nightly versions based on the nightly wasm binaries provided by kiwix-build, e.g. https://download.openzim.org/nightly/2022-12-13/, and also that the default for a Release build is to use the latest released binaries from kiwix-build.

Thank you very much for all your hard work and collaboration that made this possible. 😊 I've [released v0.1](https://github.com/openzim/javascript-libzim/releases/tag/v0.1) based on [latest kiwix-build release](https://download.openzim.org/release/libzim/libzim_wasm-emscripten-8.1.0-1.tar.gz).

I've retained the ability to build everything from source for reasons of troubleshooting and customization (especially relating to #17 and #11).

**Comment by kelson42** [comment]
@mgautierfr @Jaifroid Pretty glad to see this finally happening. Kudos to borh of you and @mossroy and @dattaz for the initial push.
