### ISSUE TITLE
Decide what to do with the two test implementations in this Repo

### ISSUE THREAD

**Issue by Jaifroid** [openzim/javascript-libzim#21]
This is an issue [mentioned by @kelson42](https://github.com/openzim/javascript-libzim/pull/14#issuecomment-1336489147) in #14 about not committing binaries in the Repository. As a result of the comments, I have in #14 moved (temporarily?) the two test implementations, including their required WASMs, into a new directory `/tests/`. The issue is that, for the tests to work, the WASMs and wrappers for each test currently need to be committed in the respective directories AFAIK (and currently would have to be updated manually). This issue is to decide if this solution is OK, or if another one is available that doesn't lose the test implementations.

Once merged, the two implementations will be available at:

* `tests/prototype/`
* `tests/test_large_file_access/`

The demo will no longer launch directly from the home page (e.g. on GitHub pages). However, I could add a redirect to the prototype version from the home page if it would be useful.

As mentioned, the dependencies in these implementations are not automatically updated. The push / PR workflow does (internally) write new files to these implementations for any potential Unit tests we could run with them, but does not of course commit the changes.

**Comment by Jaifroid** [comment]
In https://github.com/openzim/javascript-libzim/issues/41#issuecomment-1368241420, @kelson42 wrote:

> @Jaifroid It's still not clear if this is really needed in this form and why, but I see 3 possible scenarios (in order of preference for me):
> 
> 1. We consider that this is a dev tool and that developers can do the necessary themself (locally), so all these generated files can vanish from the git. Probably a README would be needed to explain how to setup the service locally.
> 2. We put this demo stuff in an other repository
> 3. We ignore the files (then I would need the list)

Well as I mentioned, I found this demo very useful for understanding how to integrate search into Kiwix JS apps, and IMHO it would be a shame (for an open-source project) if we didn't provide such a demo somewhere. I could of course move it to Kiwix JS, but I wonder if that isn't just moving the problem elsewhere, while the files the demo uses are generated here. On the face of it, it would seem to me that the logical place for a demo of how to use files generated by this Repo is in this Repo... But I also understand the problems caused by committing binaries to the Repo even if only for demo/testing purposes.

Perhaps @mgautierfr has a view, given that I'm aware he has used the demo to test files he has generated with Emscripten (and maybe also had a hand in authoring the demo?). The third option above relates to #41 (ignoring the generated JavaScript in codefactor).

**Comment by mgautierfr** [comment]
I agree with @kelson42, generated files must not be included in the git repository.

It is ok to have `test/test_large_file_access/large_file_access.js` or `test/test_large_file_access/index.html` in the repository as they are not generated.
But any `*-wasm.js` file are generated/compiled file and should not be included.

The situation is pretty the same for (cpp) libzim. https://github.com/openzim/libzim/tree/main/examples files are source file and need a compiled library to be usable. It is a good thing to have example files but we don't have to provide ready to use compiled file in the repository. I know this is a bit disturbing for the web as at origin, source were directly usable but we are in enscriptem here not simple web (and web projects now also provide minified/packaged js using CDN and keep source only in their repositories)

So I think example files (source) must be included in the git repository.
Wasm file must be compiled by the user (with a readme telling how to do it). For simplification, we could publish a pre-compiled version (as we publish a compiled version of libzim) but it should be done on `https://download.openzim.org`

**Comment by Jaifroid** [comment]
OK, thanks for the advice, both. So I'll get rid of the demos and will instead provide instructions on how to compile the demos. NB The `large_file_access.js` is in fact generated by the makefile [here](https://github.com/openzim/javascript-libzim/blob/main/Makefile#L97).

Maybe the best thing is to have a node/NPM script that generates the demos for a user/dev who has cloned the Repo, so it's easy to make.

**Comment by mgautierfr** [comment]
> Maybe the best thing is to have a node/NPM script that generates the demos for a user/dev who has cloned the Repo, so it's easy to make.

Definitively. This is what is made on libzim with the meson build system.

**Comment by Jaifroid** [comment]
Slight complication: as I need to raise an issue over at Emscripten regarding WORKERFS not supporting large files on Android, I need to be able to point to a test case (Kripken almost always asks for a test case when issues are raised). It reminds me that this is the reason the big files test case was made in the first place. So I think the demos need to stick around for a bit longer, unfortunately, until the wrinkles are ironed out.

**Comment by mgautierfr** [comment]
Could it be put in another repository or in a gist (https://gist.github.com/) ?

**Comment by Jaifroid** [comment]
> Could it be put in another repository or in a gist (https://gist.github.com/) ?

Yes, I could add it to the Kiwix JS repository, since we have to have binaries committed there anyway (for the PWA version of the app to function). Thanks also for the gist suggestion. I had forgotten about that possibility.

**Comment by Jaifroid** [comment]
Tests in #62 depend on the prototype, because I have to run tests in Browser context, and they don't work in Node context. I tried lots of things to make the latter work, but ran into many issues, due to use of browser-only APIs in the binding code, and in particular due to lack of Web Worker support in Node (it has its own worker-thread API, but it is too different).
