### ISSUE TITLE
Add SSH_KEY secret to this repository

### ISSUE THREAD

**Issue by Jaifroid** [openzim/javascript-libzim#23]
@rgaudin As @kelson42 mentioned in https://github.com/openzim/javascript-libzim/issues/14#issuecomment-1336120894, could you kindly push here the necessary secret(s) so we can upload to https://download.openzim.org/release/javascript-libzim from this repo?

I would do it myself, but I don't seem to have the right access to this Repo to be able to see or add secrets (or any configuration). I have created a workflow that uses `${{ secrets.SSH_KEY }}`, but I'm being warned that this key doesn't exist.

Many thanks!

**Comment by rgaudin** [comment]
Added `SSH_KEY` secret and made @Jaifroid admin on the repo.

**Comment by Jaifroid** [comment]
@rgaudin Thank you very much for the swift response!
