### ISSUE TITLE
Concerns about licensing

### ISSUE THREAD

**Issue by JacksonChen666** [openzim/javascript-libzim#27]
I noticed that this repository (and what it was forked from) does not contain a license.
I think it's best that before this project goes any further, it should be known that [no license means no permission](https://choosealicense.com/no-permission/) to do things with the code, and a license grants those permissions. A license should be added, but the problem is I don't know what the license for [the repo it was forked from](https://github.com/dattaz/libzim_wasm).

**Comment by kelson42** [comment]
I confirm! I wanted to fix and have forgotten to commit/push the gpl3 LICENSE file.

**Comment by JacksonChen666** [comment]
@kelson42 what about [upstream](https://github.com/dattaz/libzim_wasm)? it doesn't have a license
