### ISSUE TITLE
Update references to emscripten/emsdk

### ISSUE THREAD

**Issue by rgaudin** [openzim/javascript-libzim#46]
Within https://github.com/kiwix/overview/issues/82, we looked at all repos for dependency on Docker Images that may migrate out of Docker Hub.

You use `emscripten/emsdk:3.1.12` as your base image. [emscripten](https://hub.docker.com/u/emscripten) is a *Community Organization*.

While this specific image shall remain available (unless emscripten decides to), it is possible that emscripten decides to push future images to a different registry (alternatives being to pay a subscription to Hub or get accepted in their OSS Program).

You should probably find out what will happen and adjust your scripts accordingly.

See https://github.com/kiwix/kiwix-js/issues/980

**Comment by Jaifroid** [comment]
It seems Emscripten continues to use Docker Hub.

**Comment by Jaifroid** [comment]
OK, so for now I'll close. Many thanks.
