### ISSUE TITLE
[REGRESSION] Full-text searching is broken when building from libzim nightly and release binaries (libzim 8.2.1)

### ISSUE THREAD

**Issue by Jaifroid** [openzim/javascript-libzim#58]
I could have sworn I tested full-text searching, and it was working with one of the test builds. But now it most definitely isn't. [EDIT: it appears I had tested full-text searching only on the manual test build, and forgot to test it on the test builds built from `libzim.a`.]

This needs investigating. In the meantime, I have added a notice to the release page signalling that v0.2 should be used until the cause of this has been found and we can release a corrected v0.4.

**Comment by Jaifroid** [comment]
@kelson42 In the light of this, would it be best if I removed the artefacts from the Release on GitHub, and also from download.openzim.org/releases? Or do we just leave them and have them superseded with 0.4 when fixed?

**Comment by Jaifroid** [comment]
(I'm probably the only person currently using these releases, so I doubt anyone else is affected.)

**Comment by Jaifroid** [comment]
OK, so artefacts built manually (from scratch, without libzim.a) appear to be working correctly. The artefacts attached to this manual build are working fine:

https://github.com/openzim/javascript-libzim/actions/runs/6493054431

I could prepare a release 0.4 with manually built artefacts, as an interim until we discover the cause of the discrepancy.

**Comment by Jaifroid** [comment]
Some diagnostics from the broken release 0.3 binaries (using the dev version of the WASM from the release artefacts and deploying them to a locally served copy of the test prototype in `/tests/prototype/`. This error manifests when trying to search any ZIM archive (text pasted after image). All other functions tested in the prototype work, only search is broken. I'll try to confirm by building again from libzim binaries, then building manually, and seeing what the differences are, and if the error persists.

![image](https://github.com/openzim/javascript-libzim/assets/4304337/1fb5b625-63a2-4941-ae47-cf57504e739b)

```
Uncaught RuntimeError: memory access out of bounds
    at zim::removeAccents(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const&) (libzim-wasm.dev.wasm:0x292a8)
    at zim::InternalDataBase::parseQuery(zim::Query const&) (libzim-wasm.dev.wasm:0x2addc)
    at zim::Search::getEnquire() const (libzim-wasm.dev.wasm:0x2b5e3)
    at zim::Search::getResults(int, int) const (libzim-wasm.dev.wasm:0x2b743)
    at invoke_viiii (libzim-wasm.dev.js:7485:29)
    at search(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, int) (libzim-wasm.dev.wasm:0x87fd)
    at invoke_viii (libzim-wasm.dev.js:7441:29)
    at emscripten::internal::Invoker<std::__2::vector<EntryWrapper, std::__2::allocator<EntryWrapper>>, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, int>::invoke(std::__2::vector<EntryWrapper, std::__2::allocator<EntryWrapper>> (*)(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, int), emscripten::internal::BindingType<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, void>::'unnamed'*, int) (libzim-wasm.dev.wasm:0xcb3a)
    at Object.search (libzim-wasm.dev.js:5578:33)
    at libzim-wasm.dev.js:50:37
```

**Comment by Jaifroid** [comment]
I can now confirm the following: building from the `libzim.a` in both `libzim_wasm-emscripten-8.2.1` and in the latest nightly (`lizim_wasm-emscripten-2023-10-13`) makes semi-broken WASM and ASM binaries. They can read articles in a ZIM, but they crash when undertaking full-text (Xapian-based) search. However, if I build manually from `libzim-8.2.1` source files (not using `libzim.a`), the resulting binaries are fully working.

In addition to the tests logged above, I have just conducted the following tests to confirm this issue:

* Release artefacts in (draft) release 0.4 (manually built from scratch with `libzim-8.2.1.tar.xz` and the makefile in this repository) are working fine;
* Nightly artefacts in https://download.openzim.org/nightly/2023-10-13/ built three hours ago ([build log here](https://github.com/openzim/javascript-libzim/actions/runs/6503309724/job/17663594960)) built with `libzim.a` contained in https://download.openzim.org/nightly/2023-10-13/libzim_wasm-emscripten-2023-10-13.tar.gz are broken (full-text search gives the above errors);
* Artefacts in release 0.3 made yesterday ([build log here](https://github.com/openzim/javascript-libzim/actions/runs/6495921022/job/17641809634)) with https://download.openzim.org/release/libzim/libzim_wasm-emscripten-8.2.1-1.tar.gz are broken with errors logged above.

@mgautierfr This strongly suggests that there is a build issue affecting the inclusion of Xapian upstream in `libzim.a`. Are you aware of any issue in your pipeline? The only alternative I can think of is an incompatibility (e.g., different Emscripten version?) between the build process of `libzim.a` and the build process that converts it to WASM/ASM here. However, the fact that the binaries are only partially broken (only full-text search affected) suggests the former. Any ideas?

**Comment by kelson42** [comment]
This is essential libzim-wasm work. Everything possible should be done to fix this bug. The key question is how urgent is that?

**Comment by Jaifroid** [comment]
@kelson42 It's not very urgent because I have released a working version from source, as the issue **appears** (unconfirmed) to be in the `libzim.a` binary, or possibly in the interaction between the binary and the conversion to WASM/ASM here.

**Comment by kelson42** [comment]
@Jaifroid I'm not happy to release anything compiled on the computer of a developer. This is taboo and should be avoided. Based on this, how urgent is this ticket? If libzim release is NOK! Please opena ticket at openzim/libzim as well.

**Comment by Jaifroid** [comment]
No, it was built on GitHub actions with the workflow here: https://github.com/openzim/javascript-libzim/actions/runs/6501281292/job/17658318317.

**Comment by Jaifroid** [comment]
This [build workflow](https://github.com/openzim/javascript-libzim/actions/workflows/build_libzim_wasm.yml) has three build options provided when dispatching:

* from source (what I referred to as building "manually", but I realize it's misleading);
* from release (from `libzim.a` in latest libzim release)
* from nightly (from `libzim.a` in latest libzim nightly)

Regarding opening a ticket at openzim/libzim -- I thought I should do that after @mgautierfr confirms that the problem (might be) upstream.

**Comment by kelson42** [comment]
@Jaifroid Do we know if any official build of libzim was not suffering if this problem in the past?

**Comment by Jaifroid** [comment]
I have not encountered the problem before v8.2.1.

In terms of official releases in this Repo, they have been extensively tested and confirmed to be working with the exception of the fated 0.3 release (insufficiently tested prior to release _mea culpa_  -- more haste, less speed...).

Releases in this repo correspond to the following libzim versions:

* v0.0.1 corresponds to libzim 7.2.2 built from source;
* v0.0.2 corresponds to libzim 8.1.0 built from source;
* v0.1 corresponds to libzim 8.1.0 built from libzim binary `libzim.a`;
* v0.2 corresponds to libzim 8.1.0 built from libzim binary `libzim.a`;
* v0.3 corresponds to libzim 8.2.1 built from libzim binary `libzim.a` (BROKEN);
* v0.4 corresponds to libzim 8.2.1 built from source

**Comment by kelson42** [comment]
@mgautierfr @Jaifroid OK, so we face a regression. Beside fixing this bug we will need to see if we can figure out how to avoid this in the future.

**Comment by Jaifroid** [comment]
I guess the way to avoid it woruld be to add Unit Tests for the implemented bindings, which are: read article count, read directory entry and Blob by path, and full search.

**Comment by Jaifroid** [comment]
Our posts crossed! Yes, I can do that using the prototype implementation.

**Comment by mgautierfr** [comment]
> Releases in this repo correspond to the following libzim versions:
>
> - v0.0.1 corresponds to libzim 7.2.2 built from source;
> - v0.0.2 corresponds to libzim 8.1.0 built from source;
> - v0.1 corresponds to libzim 8.1.0 built from libzim binary libzim.a;
> - v0.2 corresponds to libzim 8.1.0 built from libzim binary libzim.a;
> - v0.3 corresponds to libzim 8.2.1 built from libzim binary libzim.a (BROKEN);
> - v0.4 corresponds to libzim 8.2.1 built from source

The yesterday commit https://github.com/openzim/javascript-libzim/commit/7cc39dafc4f1efe641faf6c4446ff523405fbb66 change the libzim version from `8.2.0` to `8.2.1`. 
Was it working with `8.2.0` ?

**Comment by Jaifroid** [comment]
@mgautierfr We never built or released a version based on 8.2.0 (unless there might have been some untested nightlies built on that version, but it would have been over a month ago). I can build that version in a branch to see if it works.

**Comment by Jaifroid** [comment]
Oh, sorry I see in fact the previous nightlies this month should be built on that veision. Let me check.

**Comment by Jaifroid** [comment]
No, we're out of luck, the nightlies were built on the latest nightly from libzim, and the repo was not producing nightlies for over a month, so previous builds have gone. I'll build artefacts in a branch so we can test.

**Comment by mgautierfr** [comment]
Can you test with this version https://tmp.kiwix.org/ci/dev_preview/emsdk/libzim_wasm-emscripten-2023-10-13.tar.gz ?

It is the "nightly" but with the same emsdk version than the one you are using.

**Comment by Jaifroid** [comment]
> Can you test with this version https://tmp.kiwix.org/ci/dev_preview/emsdk/libzim_wasm-emscripten-2023-10-13.tar.gz ?
> 
> It is the "nightly" but with the same emsdk version than the one you are using.

I've tested also with that one in https://github.com/openzim/javascript-libzim/actions/runs/6508604633, and unfortunately it gives the same error with search (see screenshot). In case you want to verify, the artefacts are attached to the workflow (bottom of workflow screen).

![image](https://github.com/openzim/javascript-libzim/assets/4304337/9d316ed3-666d-4d34-b639-0b961831915a)

**Comment by Jaifroid** [comment]
So, to summarize, v8.2.0 builds correctly from libzim binary (`libzim.a`), as documented in #60, but neither v8.2.1, nor the temporary build #61, are working. ☹️

**Comment by mgautierfr** [comment]
I suspect this PR: https://github.com/openzim/libzim/pull/797

However, it is strange that when you compile it yourselves, is doesn't crash.

**Comment by Jaifroid** [comment]
I wonder if you might be able to spot any clue in the source build logs here: https://github.com/openzim/javascript-libzim/actions/runs/6501281292/job/17658318317#step:6:8135 (around line 8134 is where the compilation of libzim.a begins in the source build). Just before this, Xapian is compiled. Are we using different versions? I haven't updated the fixed versions in the build, I only updated lizim source code to 8.2.1. (Please ignore the commented out line that points to an old 7.2.2 version of libzim source code; that was just a comment left in the makefile.)

To be clear, this is a build from source that works.

**Comment by mgautierfr** [comment]
What is the content of `emscripten-crosscompile.ini` ?
How do you compile ICU ? (If you do)
If not, where does it come from ?

**Comment by Jaifroid** [comment]
@mgautierfr I don't know that level of detail, I'm afraid, because the repo was originally set up by dattaz and then mossroy. I merely took over a working version and tweaked it the best I could. It's complex, low-level stuff (for me, as I have no background in C++).

**Comment by mgautierfr** [comment]
Ok, when compiling from source, you use ICU 71.1 https://github.com/openzim/javascript-libzim/blob/main/Makefile#L52

Then when you compile the wasm.js you link with ICU (`-licui18n -licuuc -licudata`). So probably the ICU just installed.

When using the published libzim, you just link with ICU. The library is the one in the docker and it seems to be version 70.1 (https://github.com/openzim/javascript-libzim/actions/runs/6501281292/job/17658318317#step:3:266)

However, we are building libzim with ICU 58 https://github.com/kiwix/kiwix-build/blob/main/kiwixbuild/dependencies/icu4c.py#L14
And for wasm, we configure with option `--with-data-packaging=archive` (https://github.com/kiwix/kiwix-build/blob/main/kiwixbuild/dependencies/icu4c.py#L48), which means we store the data in a `icudt58.dat` (which is not released).

So I suspect there is a conflict between the ICU version when you use the precompiled version.
But it is not explaining why it works with 8.2.0.

You have changed the ICU version here : https://github.com/openzim/javascript-libzim/commit/27e4ef79b5275546aa5d31fd3205323c27d9fe9d Do you think it may be related ?

**Comment by Jaifroid** [comment]
> You have changed the ICU version here : [27e4ef7](https://github.com/openzim/javascript-libzim/commit/27e4ef79b5275546aa5d31fd3205323c27d9fe9d) Do you think it may be related ?

I can't remember much about that change. I believe I was trying to get the source-code compilation to work on a more modern Emscripten, because for a long time we were stuck on an old version, and the makefile wouldn't compile on anything greater than that version. Following up errorcodes I must have been advised at some point to change that ICU version. In any case, it did the trick and allowed us to move the version of Emscripten to the (then) latest, and to be in sync with the version of Emscripten that you were using (then).

I wish I could answer your question, but I suspect you have a lot better idea of the impact of this than I do. Clearly none of that part of the makefile runs when building from precompiled `libzim.a`, because `icudata.so` is only needed to build `libzim.a`.

Would it be problematic for you to change your version of icu -- if I've understood correctly, it would be an upgrade from 58 to 71?

**Comment by Jaifroid** [comment]
(Of course, I meant on a trial-and-error basis, as we're not even sure that's the issue.)

**Comment by Jaifroid** [comment]
@mgautierfr @kelson42 I have complete #59 as requested, and as you can see from https://github.com/openzim/javascript-libzim/actions/runs/6606727855/job/17943238231, the new tests are now systematically failing on the Xapian search test on standard builds from libzim binaries. Nightly builds will also fail, and therefore no nightlies will be uploaded to the download server until this issue is fixed (unless I switch to using source builds):

![image](https://github.com/openzim/javascript-libzim/assets/4304337/c1be62c7-5e31-4e39-950c-6d4f6567949d)

When building from source, the tests pass, as designed, because Xapian searching works when using the all: macro in the makefile in this Repo. A source build can be triggered from the workflow dispatch [here](https://github.com/openzim/javascript-libzim/actions/workflows/build_libzim_wasm.yml). All tests passing correctly with the source workflow can be seen in https://github.com/openzim/javascript-libzim/actions/runs/6606592181/job/17942944428 and in this screenshot:

![image](https://github.com/openzim/javascript-libzim/assets/4304337/3f5cb1f9-e8d9-4ecf-b72f-23e615bb8587)

So, now we have a reliable test, we actually need to fix the issue...

**Comment by Jaifroid** [comment]
And as expected, the latest scheduled nightly failed due to this issue (4 tests passed, 1 test failed): https://github.com/openzim/javascript-libzim/actions/runs/6608000995/job/17946110156.

**Comment by mgautierfr** [comment]
@Jaifroid Can you test with https://tmp.kiwix.org/ci/dev_preview/update_icu/libzim_wasm-emscripten-2023-11-02.tar.gz ?
It correspond to build for kiwix/kiwix-build#644. It updates ICU to the last version 73.2.
If it is ok on your side, we merge it.

**Comment by Jaifroid** [comment]
OK, will do.

**Comment by Jaifroid** [comment]
The automated tests are passing with that package: see https://github.com/openzim/javascript-libzim/actions/runs/6733046741.

I'll do a manual check now with the archived binaries attached to that workflow.

**Comment by Jaifroid** [comment]
Although the manual test works on Ray Charles, it's failing with an "uncaught" error on a Stackexchange ZIM. I wonder what that could be?
![image](https://github.com/openzim/javascript-libzim/assets/4304337/dd48c793-c3b9-4878-ad22-baf13f2b11b5)

**Comment by Jaifroid** [comment]
Getting same issue with `phet_es_2023-01.zim`:

![image](https://github.com/openzim/javascript-libzim/assets/4304337/19f30bba-6dad-458e-8651-c162a1252f08)

Let me check that it's this build and not also present with a previous working build.

**Comment by Jaifroid** [comment]
OK, that issue doesn't seem to have anything to do with this build. Sadly, it goes all the way back to v0.0.2 (and v0.0.1 was too unstable to run), and that build was built from source. Also present in v0.4 built from source. So it's a different issue.

So long as you are not getting errors in other libzims on, for example, `beer.stackexchange.com_en_all_2023-05.zim` or `phet_en_all_2023-04.zim`, I think it's clear this is not a problem on your side, and is probably something to do with issues reported in https://github.com/kiwix/kiwix-js/issues/872. Could be an out of memory issue. I need to build the WASM with full assertions to debug.

This version works fine for Xapian search, which is what we're currently using it for. I'll investigate further when I get round to integrating libzim with Kiwix JS properly (but for now as an option).

**Comment by Jaifroid** [comment]
Note to future self (I'll reference this somewhere else, but it could be interesting info for now): both of the referenced ZIMs in previous comment have a number of directory entries that the service worker attempts to load when loading the landing page, but are not found in the archive. See screenshot below which is from our current implementation with the `beer.stackexchange` ZIM. I strongly suspect that the libzim builds in general (nothing to do with this specific build) don't cope well with not-found directory entries and are throwing an error internally. This is clearly not being handled well, maybe in our glue, or maybe at some other level. Probably need some error catching in the glue. I'll open a separate issue.

![image](https://github.com/openzim/javascript-libzim/assets/4304337/147e35a8-8dd2-4cf2-85bd-3682ed84c395)

**Comment by kelson42** [comment]
@Jaifroid Sad to read you face now another issue which you seem now to track in #64 and which is another issue and this is not clear exactly what is going on there.

Therefore, can we close this issue and https://github.com/openzim/libzim/issues/828 which is a blocker for the release of libzim `9.0.0`?

**Comment by Jaifroid** [comment]
@kelson42 Yes, this issue is dealt with, and have put the new issue in #64.
