### ISSUE TITLE
Implement CI with automated tests

### ISSUE THREAD

**Issue by kelson42** [openzim/javascript-libzim#59]
Tests for the implemented bindings, which are: read article count, read directory entry and Blob by path, and full search.

Following https://github.com/openzim/javascript-libzim/issues/58#issuecomment-1761194796

**Comment by Jaifroid** [comment]
Tests in #62 are now complete and working as intended. Note that this means that when I merge, tests will be failing on every run, because current libzim binaries are broken for building WASM with this repository. Note that tests pass if I initiate a run from source.
